In [1]:
import numpy as np

### From Python list

In [3]:
my_list = [4,6,3,6,9]
my_list

[4, 6, 3, 6, 9]

In [2]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros and ones

Generate arrays of zeros or ones

### linspace
Return evenly spaced numbers over a specified interval.

## eye

Creates an identity matrix

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [21]:
np.random.rand(3)

array([0.24021304, 0.29352532, 0.92100871])

In [46]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [22]:
np.random.randn(2)

array([ 0.42620726, -0.39024736])

In [23]:
np.random.randn(5,5)

array([[ 1.21382642,  2.34697672, -0.8708024 ,  0.64534389, -1.62097598],
       [-0.630677  ,  2.2435754 ,  0.20023548, -0.45762126,  0.25663389],
       [-0.45977171, -0.15464403, -0.14477493, -0.67914867, -1.37803998],
       [-1.94845477, -1.04603939, -0.27959778,  1.07713029, -0.07594146],
       [ 0.00937235,  1.38655123,  1.31178501,  0.33864928,  3.06466437]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [24]:
np.random.randint(1,100)

18

In [25]:
np.random.randint(1,100,10)

array([95, 19, 19, 91, 32, 76, 20, 99,  5, 18])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [55]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Returns an array containing the same data with a new shape.
.reshape(...) . But the number of items should remain the same

In [32]:
np.random.rand(1,200).reshape(10,20)

array([[0.94144501, 0.78447552, 0.34612753, 0.22692987, 0.40257054,
        0.53153569, 0.00470257, 0.659604  , 0.11451079, 0.78821566,
        0.87258485, 0.64057708, 0.15977792, 0.61307877, 0.01586517,
        0.84379269, 0.78104921, 0.22206928, 0.011888  , 0.43371191],
       [0.1683789 , 0.42160291, 0.38834345, 0.96836253, 0.26103521,
        0.24027113, 0.7254873 , 0.56578735, 0.54088168, 0.88061428,
        0.41699492, 0.09178144, 0.57420261, 0.56716857, 0.54306617,
        0.18255181, 0.77772968, 0.8825862 , 0.87672028, 0.58370821],
       [0.79007486, 0.45887435, 0.38256062, 0.37114852, 0.96572059,
        0.67585867, 0.98988281, 0.14086691, 0.48746489, 0.97036576,
        0.37850985, 0.64183327, 0.14337792, 0.51916619, 0.51755342,
        0.30918827, 0.37032655, 0.15107263, 0.06526144, 0.86109371],
       [0.99208935, 0.36548855, 0.28590572, 0.44747473, 0.77134446,
        0.7623538 , 0.90432569, 0.6940278 , 0.76471616, 0.54440829,
        0.05399826, 0.53516061, 0.76335065, 0

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

### dtype

You can also grab the data type of the object in the array:
arr.dtype