# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

- Get a value at an index

- Get a value in a range

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

- Set a value with index range broad cast a value.
- a[0:5] = 300

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [10]:
bool_arr = arr>4

In [11]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [12]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])